### ISSUE TITLE
Preset paths for traveling along background (avoid animals etc)

### ISSUE THREAD

**Issue by Jjef** [COMP523Trauma/EducationalPatientGames#2]

**Comment by Jjef** [comment]
Instead of programming a path which seems tedious and difficult and potentially inefficient I vote we make an object for intersections. When a sprite (such as a biker) intersects this object it simply changes direction. Seems like an easy solution and I plan to code something up if no one beats me to it but wanted to stop people from coding a harder solution if possible.

**Comment by devmariebea** [comment]
This sounds like a great idea
